# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    types: [ close ]
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.11.0'

      - name: make CHANGELOG.md
        run: |
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
          git-chglog --next-tag upcoming -o CHANGELOG.md

      - name: push CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "generate CHANGELOG.md"
          git push origin master
